<?php
// `config.php` IS NOT YOUR config file.
// `config.local.php` IS YOUR config file.
// Copy `config.php` to `config.local.php` then fill it with your informations.

define('DOCUMENT_ROOT', 'DOCUMENT ROOT OF YOUR SITE (FOR EXAMPLE /var/www/html)');
define('DEV', '(TRUE IF THE SITE IS ON DEV MODE AND FALSE OTHERWISE)');

// MySQL
define('DB_STRING', 'mysql:host=localhost;dbname=YOUR_DATABASE;charset=utf8mb4');
define('DB_USER', 'YOUR DB USER');
define('DB_PSW', 'YOUR DB PASSWORD');

// SMTP
define('SMTP_HOST', 'YOUR SMTP HOST');
define('SMTP_PORT', 587);
define('SMTP_USERNAME', 'YOUR SMTP USERNAME');
define('SMTP_PSW', 'YOUR SMTP PASSWORD');
define('SMTP_MAIL', 'YOUR E-MAIL ADDRESS USE TO SEND MAILS');
define('SMTP_NAME', 'YOUR NAME USE TO SEND MAILS');

// Flarum
define('FLARUM_URL', 'YOUR FLARUM URL');
define('FLARUM_TOKEN', 'YOUR FLARUM TOKEN');
define('FLARUM_USERID', 'YOUR FLARUM ADMIN USERID');
define('FLARUM_SHORT_DOMAIN', 'YOUR FLARUM BASE DOMAIN (SHORT E.G. progaccess.net)');

// Twitter
define('CONSUMER_KEY', 'YOUR TWITTER CONSUMER KEY');
define('CONSUMER_SECRET', 'YOUR TWITTER CONSUMER SECRET');
define('ACCESS_TOKEN', 'YOUR TWITTER ACCESS TOKEN');
define('ACCESS_TOKEN_SECRET', 'YOUR TWITTER ACCESS TOKEN SECRET');

// Facebook
define('FB_APP_ID', 'YOUR FACEBOOK APP ID');
define('FB_APP_SECRET', 'YOUR FACEBOOK APP SECRET');
define('FB_TOKEN', 'YOUR FACEBOOK TOKEN');

// Mastodon
define('MASTODON_TOKEN', 'YOUR MASTODON APP ACCESS TOKEN');
define('MASTODON_URL', 'YOUR MASTODON INSTANCE URL');
define('MASTODON_VISIBILITY', 'VISIBILITY OF TOOTS POSTED ON MASTODON (PUBLIC, PRIVATE, UNLISTED OR DIRECT)');
define('MASTODON_LANG', 'LANGUAGE OF TOOTS POSTED ON MASTODON (EN, FR, ZH...)');

// Git
define('GIT_DIR', 'PATH OF .GIT FOLDER');
define('GIT_COMMIT_BASE_URL', 'BEGIN URL OF A COMMIT ON YOUR GIT REPO');
define('GIT_WEBHOOK_TOKEN', 'GIT WEBHOOK TOKEN TO AUTHENTIFY REPO');

// Discord
define('DISCORD_WEBHOOK_URL', 'URL OF DISCORD WEBHOOK TO POST ON YOUR SERVER');

// Site
define('SITE_NAME', 'NAME OF YOUR WEBSITE');
define('SITE_URL', 'BASE DOMAIN OF YOUR WEBSITE');

// Specific to admin menu
define('WEBMAIL_URL', 'URL OF YOUR WEBMAIL');
define('WEBMAIL_NAME', 'NAME OF YOUR WEBMAIL');
define('CONTROLPANEL_URL', 'URL OF YOUR SERVER CONTROL PANEL');
define('CONTROLPANEL_NAME', 'NAME OF YOUR SERVER CONTROL PANEL');
?>
